// <auto-generated />
using System;
using AI.ChatAgent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AI.ChatAgent.Migrations
{
    [DbContext(typeof(ChatAgentDbContext))]
    partial class ChatAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AI.ChatAgent.Models.ChatMessage", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("SessionId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Role").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.Property<string>("Content").IsRequired().HasColumnType("TEXT");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
                b.Property<int?>("TokenCount").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("SessionId");
                b.HasIndex("CreatedAt");
                b.ToTable("ChatMessages");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.ChatSession", b =>
            {
                b.Property<string>("Id").HasColumnType("TEXT");
                b.Property<string>("Title").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTimeOffset>("LastActivityAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("ChatSessions");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.Customer", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasMaxLength(254).HasColumnType("TEXT");
                b.Property<string>("Phone").HasMaxLength(20).HasColumnType("TEXT");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Customers");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.Order", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("CustomerId").HasColumnType("INTEGER");
                b.Property<decimal>("TotalAmount").HasColumnType("decimal(18,2)");
                b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("TEXT");
                b.Property<DateTimeOffset>("OrderDate").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("CustomerId");
                b.HasIndex("Status");
                b.HasIndex("OrderDate");
                b.ToTable("Orders");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.OrderItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("OrderId").HasColumnType("INTEGER");
                b.Property<int>("ProductId").HasColumnType("INTEGER");
                b.Property<int>("Quantity").HasColumnType("INTEGER");
                b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.HasIndex("ProductId");
                b.ToTable("OrderItems");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.Product", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("TEXT");
                b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                b.Property<string>("Category").HasMaxLength(100).HasColumnType("TEXT");
                b.Property<int>("StockQuantity").HasColumnType("INTEGER");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("Category");
                b.HasIndex("IsActive");
                b.ToTable("Products");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.ChatMessage", b =>
            {
                b.HasOne("AI.ChatAgent.Models.ChatSession", "Session")
                    .WithMany("Messages").HasForeignKey("SessionId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Session");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.Order", b =>
            {
                b.HasOne("AI.ChatAgent.Models.Customer", "Customer")
                    .WithMany("Orders").HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Customer");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.OrderItem", b =>
            {
                b.HasOne("AI.ChatAgent.Models.Order", "Order")
                    .WithMany("Items").HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Order");
                b.HasOne("AI.ChatAgent.Models.Product", "Product")
                    .WithMany().HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Product");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.ChatSession", b =>
            {
                b.Navigation("Messages");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.Customer", b =>
            {
                b.Navigation("Orders");
            });

            modelBuilder.Entity("AI.ChatAgent.Models.Order", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}
